version: 1
workflows:
  api-dev:
    description: Run API with reload
    steps:
      - run: pnpm --filter api dev
  api-test:
    description: Lint + test API
    steps:
      - run: pnpm --filter api lint
      - run: pnpm --filter api test
  api-seed:
    description: Seed demo tenant/user into local DB
    steps:
      - run: DATABASE_URL=file:./apps/api/dev.db pnpm --filter api prisma db push --skip-generate --accept-data-loss
      - run: DATABASE_URL=file:./apps/api/dev.db pnpm --filter api seed
  db-seed-pg:
    description: Seed demo tenant/user into Postgres
    steps:
      - run: DATABASE_URL=postgres://nostrstack:nostrstack@localhost:5432/nostrstack pnpm --filter api prisma migrate deploy --schema prisma/pg/schema.prisma
      - run: DATABASE_URL=postgres://nostrstack:nostrstack@localhost:5432/nostrstack pnpm --filter api seed
  api-e2e:
    description: Run Playwright LNURL e2e (requires API running at localhost:3301 and PLAYWRIGHT_API_READY=1)
    steps:
      - run: PLAYWRIGHT_API_READY=1 pnpm --filter api test:e2e
  social-dev:
    description: Run demo social
    steps:
      - run: pnpm --filter social dev
  db-up:
    description: Start local Postgres via docker-compose
    steps:
      - run: docker compose up -d postgres
  db-down:
    description: Stop local Postgres
    steps:
      - run: docker compose stop postgres
