ls:
  .js: regex:^([a-z][a-z0-9]*)(-[a-z0-9]+)*$|^([a-z][a-z0-9]*)([A-Z][a-z0-9]*)*$
  .ts: regex:^([a-z][a-z0-9]*)(-[a-z0-9]+)*$|^([a-z][a-z0-9]*)([A-Z][a-z0-9]*)*$
  .d.ts: regex:^([a-z][a-z0-9]*)(-[a-z0-9]+)*$|^([a-z][a-z0-9]*)([A-Z][a-z0-9]*)*$
  .tsx: PascalCase | kebab-case
  .json: kebab-case
  .css: kebab-case
  .md: kebab-case | regex:^[A-Z_]+$
ignore:
  - '**/node_modules'
  - '**/dist'
  - '**/coverage'
  - '.git'
  - '.github'
  - '.vscode'
  - '.pnpm-store'
  - '.oracle'
  - 'apps/web/src/DMView.tsx'
  - 'apps/web/src/components/ZapModal.css'
  - 'apps/web/src/nostr/eventRenderers.tsx'
  - 'playwright-*.md'
  - 'page-*.md'
  - 'thread-*.md'
  - 'find-friend*.md'
  - 'search-*.md'
  - 'home-*.md'
  - 'qa-*.md'
  - 'playwright_*.json'
  - 'feed_after_reply.json'
