PNPM=pnpm
REPO=joelklabo/nostrstack

# Dev defaults (one secure origin, self-signed certs generated by scripts/dev-logs.sh)
DEV_CERT?=certs/dev-cert.pem
DEV_KEY?=certs/dev-key.pem
DEV_ORIGIN?=https://localhost:3001
DEV_DB?=file:./dev.db
DEV_LNBITS_URL?=http://localhost:15001

.PHONY: deps deps-prod build lint test typecheck check dev dev-api dev-gallery dev-demo e2e deploy-staging deploy-prod

deps:
	$(PNPM) install

deps-prod:
	NODE_ENV=production $(PNPM) install --frozen-lockfile --prod

build:
	$(PNPM) -r build

lint:
	$(PNPM) lint

test:
	$(PNPM) test

typecheck:
	$(PNPM) typecheck

check: lint test typecheck

dev-api:
	$(PNPM) --filter api dev

dev-gallery:
	$(PNPM) --filter gallery dev -- --host --port 4173

dev:
	@echo "Starting API + gallery with HTTPS via Vite and logging to .logs/dev"
	USE_HTTPS=true \
	HTTPS_CERT=$(DEV_CERT) \
	HTTPS_KEY=$(DEV_KEY) \
	PUBLIC_ORIGIN=$(DEV_ORIGIN) \
	DATABASE_URL=$(DEV_DB) \
	LN_BITS_URL=$(DEV_LNBITS_URL) \
	$(PNPM) dev:logs

dev-demo:
	./scripts/dev-demo.sh

e2e:
	$(PNPM) --filter api test:e2e

deploy-staging:
	gh workflow run azure-deploy-staging.yml --repo $(REPO)

deploy-prod:
	gh workflow run azure-deploy.yml --repo $(REPO)
