PNPM=pnpm
REPO=joelklabo/nostrstack

# Dev defaults (one secure origin, self-signed certs generated by scripts/dev-logs.sh)
DEV_CERT?=certs/dev-cert.pem
DEV_KEY?=certs/dev-key.pem
DEV_ORIGIN?=https://localhost:3001
DEV_DB?=file:./dev.db
DEV_LNBITS_URL?=http://localhost:15001

.PHONY: commands deps deps-prod build lint test test-ci typecheck check ci dev dev-api dev-social dev-gallery dev-demo e2e help deploy-staging deploy-prod

deps:
	$(PNPM) install

deps-prod:
	NODE_ENV=production $(PNPM) install --frozen-lockfile --prod

build:
	$(PNPM) -r build

lint:
	$(PNPM) lint

test:
	$(PNPM) test

test-ci:
	$(PNPM) test:ci

typecheck:
	$(PNPM) typecheck

ci:
	$(PNPM) lint
	$(PNPM) typecheck
	$(PNPM) test:ci

check: lint test typecheck

dev-api:
	$(PNPM) --filter api dev

dev-social:
	$(PNPM) --filter social dev -- --host --port 4173

dev-gallery:
	@echo "dev-gallery is deprecated; use dev-social"
	$(MAKE) dev-social

dev:
	@echo "Starting API + social with HTTPS via Vite and logging to .logs/dev"
	USE_HTTPS=true \
	HTTPS_CERT=$(DEV_CERT) \
	HTTPS_KEY=$(DEV_KEY) \
	PUBLIC_ORIGIN=$(DEV_ORIGIN) \
	DATABASE_URL=$(DEV_DB) \
	LN_BITS_URL=$(DEV_LNBITS_URL) \
	$(PNPM) dev:logs

dev-demo:
	./scripts/dev-demo.sh

e2e:
	$(PNPM) --filter api test:e2e

help:
	@echo "Core workflows:"
	@echo "  make dev            - Start API + social with HTTPS and shared logs"
	@echo "  make dev-api        - Start API only"
	@echo "  make dev-social     - Start social only"
	@echo ""
	@echo "Quality gates:"
	@echo "  make lint           - pnpm lint (all workspace lint checks)"
	@echo "  make typecheck      - pnpm typecheck"
	@echo "  make test           - pnpm test"
	@echo "  make test-ci        - pnpm test:ci"
	@echo "  make check          - lint + test + typecheck"
	@echo "  make ci             - lint + typecheck + test:ci"
	@echo "  make commands       - show canonical command catalog"

deploy-staging:
	gh workflow run azure-deploy-staging.yml --repo $(REPO)

deploy-prod:
	gh workflow run azure-deploy.yml --repo $(REPO)

commands:
	@cat docs/commands.md
