name: Build and Push to GHCR
description: Build and push a Docker image to GitHub Container Registry.

inputs:
  registry:
    description: Container registry host
    required: false
    default: ghcr.io
  image_name:
    description: Repository/image name (without registry host)
    required: true
  image_tag:
    description: Docker image tag
    required: true
  dockerfile:
    description: Path to Dockerfile
    required: true
  context:
    description: Build context path
    required: false
    default: .
  build_args:
    description: Build args in Dockerfile syntax
    required: false
    default: ''
  username:
    description: Registry username
    required: true
  token:
    description: Registry token
    required: true

outputs:
  image:
    description: Full image reference that was pushed
    value: ${{ steps.meta.outputs.image }}

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Build and push image
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: ${{ inputs.build_args }}

    - name: Set image output
      id: meta
      run: |
        echo "image=${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.image_tag }}" >> "$GITHUB_OUTPUT"
      shell: bash
